### ISSUE TITLE
Works on Linux, almost.

### ISSUE THREAD

**Issue by 0hStormy** [SandTechStuff/AeroFirefox#1]
I am currently using KDE Plasma (shouldn't matter) and Firefox 134. It's very close to working except the maximize button is too big.

![Image](https://github.com/user-attachments/assets/26c4afb4-f0b8-4995-a18e-b3fbddbb49aa)

**Comment by Sand216** [comment]
I'll set up a Linux VM when I have time to see what I can do, thanks for testing.

**Comment by 0hStormy** [comment]
Alright, thanks! I'd fix it myself but Firefox CSS doesn't have good documentation.

**Comment by Sand216** [comment]
@0hStormy At the bottom of your `userChrome.css` file, try adding:

```css
.titlebar-button > .toolbarbutton-icon{
	appearance: none;
	background-color: transparent;
}
```
If this works properly I will include it in the next release.

![Image](https://github.com/user-attachments/assets/05121b37-6b03-474b-906e-052ac7ca94af)
