### ISSUE TITLE
Improve Button Glow

### ISSUE THREAD

**Issue by Sand216** [SandTechStuff/AeroFirefox#2]
Currently, button glow is very inaccurate and could be improved.

**Comment by RagdollClash** [comment]
I got it closer by duplicating the drop-shadow filter, though I'm not sure how much of a performance impact it'll have. I also color picked from the pngs that DWMBlurGlass gives.

```css
.titlebar-close:hover > .toolbarbutton-icon{
	list-style-image: url("images/aeroCloseHover.png") !important;
	filter: drop-shadow(0px 0px 4px rgb(252, 129, 99)) drop-shadow(0px 0px 3px rgb(252, 129, 99)) drop-shadow(0px 0px 1px rgb(252, 129, 99)) !important;
}

.titlebar-max:hover > .toolbarbutton-icon{
	list-style-image: url("images/aeroMaximizeHover.png") !important;
	filter: drop-shadow(0px 0px 4px rgb(98, 206, 252)) drop-shadow(0px 0px 3px rgb(98, 206, 252)) drop-shadow(0px 0px 1px rgb(98, 206, 252)) !important;
}

.titlebar-min:hover > .toolbarbutton-icon{
	list-style-image: url("images/aeroMinimizeHover.png") !important;
	filter: drop-shadow(0px 0px 4px rgb(98, 206, 252)) drop-shadow(0px 0px 3px rgb(98, 206, 252)) drop-shadow(0px 0px 1px rgb(98, 206, 252)) !important;
}

.titlebar-restore:hover > .toolbarbutton-icon{
	list-style-image: url("images/aeroRestoreHover.png") !important;
	filter: drop-shadow(0px 0px 4px rgb(98, 206, 252)) drop-shadow(0px 0px 3px rgb(98, 206, 252)) drop-shadow(0px 0px 1px rgb(98, 206, 252)) !important;
}
```

Firefox:

https://github.com/user-attachments/assets/bda1e75d-41ca-4571-bfbf-e7ed28a615f6

DWMBlurGlass:

https://github.com/user-attachments/assets/0b154377-ba65-45f9-b0e7-e60af136941b
